version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    restart: always
    networks:
      - ecom-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: ecommerce-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - ecom-net

networks:
  ecom-net:
    driver: bridge
